export default {
  notification: '/notice',
  projects: '/project',
  putProjectLocation:'/analysis/da/project',
  projectResources: '/projectRole',
  user: '/user',
  projectVideoList: '/video',
  warning: '/warning',
  communicationList: '/ecTopic',
  communicationFollow: '/follow',
  changeSubjectStatus: '/changeStatus',
  user: '/user',
  attendanceProjectDailyList: '/attendence',
  attendanceProjectDailySummary: '/attendence',
  worker:'/worker',
  workerAttendance:'/attendence',
  environment:'/environment/latest',
  environmentAnalysis:'/environment/timeAnalysis',
  task:'/task',
  personalTask:'/personalTask',
  taskDetail:'/findBySourceId',
  dealTask:'/deal',
  projectDangers:'/analysis/da/program/project/',
  projectSalary:'/salarySheet',
  salaryDetail:'/showDetails',
  analysis:'/analysis/da',
  lifter:'/lifter/last',
  lifterAnalysis:'/lifter/timeAnalysis',
  enterprise:'/enterprise',
  integrity:'/integrity',

}


